// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyd6tCzOvJzMG4f8M_NOylK53oUY51k7M',
    appId: '1:913540702762:web:a449c75bdfcb176e889953',
    messagingSenderId: '913540702762',
    projectId: 'flus2-b1494',
    authDomain: 'flus2-b1494.firebaseapp.com',
    databaseURL: 'https://flus2-b1494-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flus2-b1494.appspot.com',
    measurementId: 'G-QH85CP86TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGu1HBHSToiWHIgAPPhxYdryAR-2gttI4',
    appId: '1:913540702762:android:96f5e2ee88c24fa6889953',
    messagingSenderId: '913540702762',
    projectId: 'flus2-b1494',
    databaseURL: 'https://flus2-b1494-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flus2-b1494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4_3uF8biclfyhR4zXL_m1GxgKdFmPIRk',
    appId: '1:913540702762:ios:64872db1d04a4adb889953',
    messagingSenderId: '913540702762',
    projectId: 'flus2-b1494',
    databaseURL: 'https://flus2-b1494-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flus2-b1494.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4_3uF8biclfyhR4zXL_m1GxgKdFmPIRk',
    appId: '1:913540702762:ios:d209bab9d895c101889953',
    messagingSenderId: '913540702762',
    projectId: 'flus2-b1494',
    databaseURL: 'https://flus2-b1494-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flus2-b1494.appspot.com',
    iosBundleId: 'com.google.firebase.presents.demo1.RunnerTests',
  );
}
